export const ApiMock = [
  { category: "Fruits", price: "$1", stocked: true, name: "Apple" },
  { category: "Fruits", price: "$1", stocked: true, name: "Dragonfruit" },
  { category: "Fruits", price: "$2", stocked: false, name: "Passionfruit" },
  { category: "Vegetables", price: "$2", stocked: true, name: "Spinach" },
  { category: "Vegetables", price: "$4", stocked: false, name: "Pumpkin" },
  { category: "Vegetables", price: "$1", stocked: true, name: "Peas" },
  { category: "Fruits", price: "$3", stocked: true, name: "Mango" },
  { category: "Fruits", price: "$2", stocked: true, name: "Banana" },
  { category: "Fruits", price: "$4", stocked: false, name: "Papaya" },
  { category: "Vegetables", price: "$1", stocked: true, name: "Carrots" },
  { category: "Vegetables", price: "$3", stocked: false, name: "Artichoke" },
  { category: "Vegetables", price: "$2", stocked: true, name: "Broccoli" },
  { category: "Fruits", price: "$5", stocked: true, name: "Pineapple" },
  { category: "Vegetables", price: "$2", stocked: false, name: "Brussels Sprouts" },
  { category: "Fruits", price: "$2.5", stocked: true, name: "Grapes" },
  { category: "Vegetables", price: "$3.5", stocked: true, name: "Asparagus" },
  { category: "Fruits", price: "$2.5", stocked: true, name: "Strawberries" },
  { category: "Vegetables", price: "$1.5", stocked: true, name: "Green Beans" },
  { category: "Fruits", price: "$4", stocked: false, name: "Kiwi" },
  { category: "Vegetables", price: "$2", stocked: true, name: "Cauliflower" },
  { category: "Fruits", price: "$3", stocked: true, name: "Blueberries" },
  { category: "Vegetables", price: "$1", stocked: false, name: "Celery" },
  { category: "Fruits", price: "$2", stocked: true, name: "Oranges" },
  { category: "Vegetables", price: "$3.5", stocked: false, name: "Eggplant" },
  { category: "Fruits", price: "$5", stocked: true, name: "Watermelon" },
  { category: "Vegetables", price: "$2.5", stocked: true, name: "Zucchini" }
];
